version: '3'
services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  dev: &dev
    build: .
    depends_on:
      - db
  
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/app
      - .bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  prod:
    <<: *dev
    ports:
      - 8000:8000
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=1
      - RAILS_MASTER_KEY
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
  
volumes:
  pgdata:
     external: true